---
- name: Destroy EC2 Instances
  hosts: localhost
  gather_facts: no
  vars:
    region: "us-east-1"
    tags:
      Name: CI-CD-Adam

  tasks:
    - name: Terminate EC2 instances
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        state: absent
        filters:
          tag:Name: "{{ tags.Name }}"

